sudo: required
language: python

services:
  - docker

install:
  - pip install coveralls==1.3.0

before_script:
  - sudo service mysql stop
  - while sudo lsof -Pi :3306 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose build

script:
  - docker-compose up -d mysql
  - docker-compose up -d redis
  - docker ps
  - docker-compose run --rm app coverage run manage.py test
  - docker-compose run --rm app coverage report -m
  - docker cp webbackend_app_run_1:/app/.coverage .

after_success:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
