sudo: required

services:
  - docker

before_script:
  - docker-compose -f compose/development.yml build

script:
  - docker-compose -f compose/development.yml up -d mysql redis
  - sleep 10; # Give time for mysql to initialize
  - docker-compose -f compose/development.yml up -d api
  - docker ps -a
  - docker-compose -f compose/development.yml exec api sh -c "cd ..; coverage run src/manage.py test;"
  - docker-compose -f compose/development.yml exec api sh -c "cd ..; coverage report -m; coverage xml; ls -lht;"

after_success:
  - docker-compose -f compose/development.yml exec api sh -c "cd ..; coveralls;"

notifications:
  email:
    on_success: never
    on_failure: always
