sudo: required

services:
  - docker

before_script:
  - sudo service mysql stop
  - while sudo lsof -Pi :3306 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose build

script:
  - docker-compose up -d mysql
  - docker-compose up -d redis
  - docker ps
  - docker-compose run --rm app coverage run manage.py test

after_success:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
